### ISSUE TITLE
3月12討論問題

### ISSUE THREAD

**Issue by ccsung16** [sebastien911/IFNLP#2]
本周的討論議題大家可以放在這裡唷!

**Comment by sunchigg** [comment]
**Q1:** List comprehension way背後是怎麼運算所以比較快的～
**Q2:** TruncatedSVD的n_iters 是怎運作～

**Comment by sebastien911** [comment]
Q3: word vector如何處理一字多義的問題？

**Comment by GitYCC** [comment]
Q4: GloVe究竟解決了word2vec的什麼問題？

**Comment by wendy81214** [comment]
Q5: 因為word2vec主要是以上下文（這個字的"用法"）來訓練word vector，所以會出現兩個字vector相似但意思差距很大的問題，不知道目前有沒有什麼已知方法解決這件事？

**Comment by YClabs** [comment]
> Q5: 因為word2vec主要是以上下文（這個字的"用法"）來訓練word vector，所以會出現兩個字vector相似但意思差距很大的問題，不知道目前有沒有什麼已知方法解決這件事？

**Comment by sebastien911** [comment]
> **Q1:** List comprehension way背後是怎麼運算所以比較快的～
> **Q2:** TruncatedSVD的n_iters 是怎運作～


Q1可以參考這裡的說明https://www.trohome.com/products/%E5%8F%AF%E8%A8%82%E8%A3%BD-%E5%AF%A6%E6%9C%A8%E6%B2%99%E7%99%BC%E5%B0%8F%E9%82%8A%E5%87%A0-1
Q2看來是有點複雜的線性代數問題XD 有找到演算法的原始paper
https://arxiv.org/pdf/0909.4061.pdf

之後再找找有沒有簡單說明抽象概念的文章

**Comment by sebastien911** [comment]
> Q3: word vector如何處理一字多義的問題？

根據lecture， 歧異字義的context vector會不同，所以可以從word vector的群落上來辨識，但這好想只回答了事後如何解讀word vector結果，沒有解決實務應用時的問題？

**Comment by sebastien911** [comment]
> Q4: GloVe究竟解決了word2vec的什麼問題？

因為是先統計corpus中的co-occurrence 才去訓練，比起word2vec隨機起始的embedding，在語料庫大小相近的狀況，應該能訓練出更好的word representation 
(找到一篇簡中解釋可以再慢慢看哈)
http://www.fanyeong.com/2018/02/19/glove-in-detail/

**Comment by sebastien911** [comment]
> Q5: 因為word2vec主要是以上下文（這個字的"用法"）來訓練word vector，所以會出現兩個字vector相似但意思差距很大的問題，不知道目前有沒有什麼已知方法解決這件事？

Here comes BERT XD
